server:
  port: 8080
  servlet:
    context-path: /order


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/order"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true