server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/SWP_DB"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: SpringOAuth2.Implementation
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
